In [1]:
import tensorflow as tf

In [3]:
x = tf.ones(shape=(2,1))
print(x)

x = tf.zeros(shape=(2,1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [4]:
x = tf.random.normal(shape=(3,1), mean=0, stddev = 1)
print(x)

x = tf.random.uniform(shape=(3,1), minval=0, maxval=1)
print(x)

tf.Tensor(
[[ 0.05974992]
 [-0.22717278]
 [ 1.0281256 ]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[0.8667294 ]
 [0.43924463]
 [0.6718596 ]], shape=(3, 1), dtype=float32)


In [7]:
v = tf.Variable(initial_value= tf.random.normal(shape=(3,1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.5995474 ],
       [ 0.31261143],
       [ 0.33996856]], dtype=float32)>


In [9]:
v.assign(tf.ones((3,1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [10]:
v[0,0].assign(3)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

In [17]:
print(v.assign_add(v))
print(v.assign_add(tf.ones((3,1))))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[402.],
       [146.],
       [146.]], dtype=float32)>
<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[403.],
       [147.],
       [147.]], dtype=float32)>


In [26]:
a = tf.random.uniform(shape=(2,2), minval=0, maxval=1)
print('Random unifrom intialization of a (2*2) matrix')
print(a)
b = tf.square(a)
print('')
print('Squaring the matrix')
print(b)
c = tf.sqrt(a)
print('')
print('Square root of the matrix')
print(c)
d = b * c
print('')
print('Squared values of a * Square root values of a - Element wise')
print(d)
e = tf.matmul(b,c)
print('')
print('Dot product of the same above')
print(e)

Random unifrom intialization of a (2*2) matrix
tf.Tensor(
[[0.6797967  0.85539436]
 [0.1052022  0.95677054]], shape=(2, 2), dtype=float32)

Squaring the matrix
tf.Tensor(
[[0.46212354 0.7316995 ]
 [0.0110675  0.91540986]], shape=(2, 2), dtype=float32)

Square root of the matrix
tf.Tensor(
[[0.8244978 0.9248753]
 [0.3243489 0.9781465]], shape=(2, 2), dtype=float32)

Squared values of a * Square root values of a - Element wise
tf.Tensor(
[[0.38101986 0.6767308 ]
 [0.00358973 0.89540493]], shape=(2, 2), dtype=float32)

Dot product of the same above
tf.Tensor(
[[0.6183458  1.143116  ]
 [0.30603734 0.905641  ]], shape=(2, 2), dtype=float32)


In [29]:
initial_value = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
  result = tf.square(initial_value) # <- TensorFlow remembers this is x^2
gradient = tape.gradient(result, initial_value)  # <- TensorFlow computes 2 * x

print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


In [32]:
input_const = tf.constant(3.)
with tf.GradientTape() as tape:
  tape.watch(input_const)
  result = tf.square(initial_value)
gradient = tape.gradient(result, initial_value)

print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


In [34]:
time = tf.Variable(0.)
with tf.GradientTape() as outer_tape:
  with tf.GradientTape() as inner_tape:
    position = 4.9 * time ** 2
  speed = inner_tape.gradient(position, time)
acceleration = outer_tape.gradient(speed, time)

print(position)
print(speed)
print(acceleration)

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(9.8, shape=(), dtype=float32)
